# Generated by Django 5.0.2 on 2024-02-21 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0002_league_user_league_prediction'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='identifier',
            field=models.CharField(default=None, max_length=12, unique=True),
            preserve_default=False,
        ),
    ]
