# Generated by Django 5.0.2 on 2024-02-23 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0002_ranking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ranking',
            name='points',
            field=models.CharField(max_length=7),
        ),
    ]
